pipeline 
{
    agent any
    parameters {
        string(name: 'BRANCH_NAME', defaultValue: 'master', description: 'Branch to build')
    }
    
    tools{
        maven 'maven'
        }

    stages 
    {
        stage('Build') 
        {
            steps
            {
                 git 'https://github.com/jglick/simple-maven-project-with-tests.git'
                 bat "mvn -Dmaven.test.failure.ignore=true clean package"
            }
            post 
            {
                success
                {
                    junit '**/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts 'target/*.jar'
                }
            }
        }
        
        
        
        stage("Deploy to QA"){
            steps{
                echo("deploy to qa done")
            }
        }
        
        
        
                
 stage('Regression Automation Tests') {
    steps {
        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
            // Clean workspace before pulling latest code
            deleteDir()

            // Pull latest code from f1 branch
            git branch: "${BRANCH_NAME}", url: 'https://github.com/cjs-001/FrameworkPOMNaveen.git'

            // Run TestNG suite with required parameters
            bat '''
                mvn -f Dec2024OpenCartFramework/pom.xml clean test ^
                    -Dsurefire.suiteXmlFiles=src/test/resources/testrunners/testng_chrome.xml ^
                    -Dbrowser=chrome -Dbrowserversion=latest ^
                    -Dtestname=RegressionRun -Dremote=false
            '''
        }
    }
}

                
     
        stage('Publish Allure Reports') {
           steps {
                script {
                    allure([
                        includeProperties: false,
                        jdk: '',
                        properties: [],
                        reportBuildPolicy: 'ALWAYS',
                        results: [[path: 'Dec2024OpenCartFramework/allure-results']]

                    ])
                }
            }
        }
        
        
        stage('Publish ChainTest Report'){
            steps{
                     publishHTML([allowMissing: false,
                                  alwaysLinkToLastBuild: false, 
                                  keepAll: true, 
                                  reportDir: 'Dec2024OpenCartFramework/target/chaintest', 
                                  reportFiles: 'Index.html', 
                                  reportName: 'HTML Regression ChainTest Report', 
                                  reportTitles: ''])
            }
        }
        
        stage("Deploy to Stage"){
            steps{
                echo("deploy to Stage")
            }
        }
        
        stage('Sanity Automation Test') {
    steps {
        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {

            // Clean workspace before pulling latest code
            deleteDir()

            // Pull latest code from f1 branch
            git branch: "${BRANCH_NAME}", url: 'https://github.com/cjs-001/FrameworkPOMNaveen.git'

            // Run TestNG suite with required parameters
            bat """
                mvn -f Dec2024OpenCartFramework/pom.xml clean test ^
                    -Dsurefire.suiteXmlFiles=src/test/resources/testrunners/testng_sanity.xml ^
                    -Dremote=false
            """
        }
    }
}
        
        
        
        stage('Publish sanity ChainTest Report'){
            steps{
                     publishHTML([allowMissing: false,
                                  alwaysLinkToLastBuild: false, 
                                  keepAll: true, 
                                  reportDir: 'Dec2024OpenCartFramework/target/chaintest', 
                                  reportFiles: 'Index.html', 
                                  reportName: 'HTML Sanity ChainTest Report', 
                                  reportTitles: ''])
            }
        }
        
        
        stage("Deploy to PROD"){
            steps{
                echo("deploy to PROD")
            }
        }
        
        
    }
}